config/routes.rb
Rails.application.routes.draw do
  root to: 'images#index'
  resources :images, except: [:edit, :update, :show]

  get '/new' => 'images#new'

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  get '/search' => 'images#search', :as => 'search_page'

  namespace :admin do 
    root to: 'images#index'
    resources :images
  end

  resources :orders, only: [:index]

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < ApplicationController
  http_basic_authenticate_with name: "Admin", password: "password123"

  def index
    @images = Image.order(id: :desc).all
  end

  def new
    @image = Images.new
  end

  def destroy
    @image = Image.find params[:id]
    @image.destroy
    redirect_to [:admin, :images], notice: 'Product deleted!'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def cart
    @cart ||= cookies[:cart].present? ? JSON.parse(cookies[:cart]) : {}
  end
  helper_method :cart

  def enhanced_cart
    @enhanced_cart ||= Image.where(id: cart.keys).map {|image| { image:image, quantity: cart[image.id.to_s] } }
  end
  helper_method :enhanced_cart

  def cart_subtotal_cents
    enhanced_cart.map {|entry| entry[:image].price_cents * entry[:quantity]}.sum
  end
  helper_method :cart_subtotal_cents


  def update_cart(new_cart)
    cookies[:cart] = {
      value: JSON.generate(new_cart),
      expires: 10.days.from_now
    }
    cookies[:cart]
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  end

  def add_item
    image_id = params[:image_id].to_s
    modify_cart_delta(image_id, +1)

    redirect_to :back
  end

  def remove_item
    image_id = params[:image_id].to_s
    modify_cart_delta(image_id, -1)

    redirect_to :back
  end

  private

  def modify_cart_delta(image_id, delta)
    cart[image_id] = (cart[image_id] || 0) + delta
    cart.delete(image_id) if cart[image_id] < 1
    update_cart cart
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all.order(created_at: :desc)
  end

  def new
    @image = Image.new
  end

  def search
    if params[:search].blank?  
      redirect_to(root_path, alert: "Empty field!") and return  
    else  
      @parameter = (params[:search].downcase << '%').prepend('%')
      @results = Image.where("lower(description) LIKE :search OR lower(name) LIKE :search OR lower(keywords) LIKE :search", search: @parameter)
    end
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      redirect_to [:images], notice: 'Image created!'
    else
      render :new
    end
  end

  private

  def image_params
    params.require(:image).permit(
      :name,
      :description, 
      :price_cents,
      :image, 
      :keywords
    )
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    empty_cart!
    @images = Image.all.order(created_at: :desc)
  end
 
  def empty_cart!
    # empty hash means no products in cart :)
    update_cart({})
  end

end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/images/_image.html.erb
<tr>
  <td>
    <%= image_tag image.image.tiny %>
  </td>
  <td>
    <h4><%= image.name %></h4>
  </td>
  <td>
    <%= image.description %>
  </td>
  <td>
  <%= image.keywords %>
</td>
  <td>$
    <%=   image.price_cents %>
  </td>

  <td>
    <%= link_to fa_icon('trash'), [:admin, image], class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: "Are you sure?" } %>
  </td>
</tr>

app/views/admin/images/index.html.erb
<section class="admin-images-index">

  <header class="page-header">
      <h1>Admin &raquo; Image Repository</h1>
  </header>

  <div class="panel panel-default products">

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th>Description</th>
          <th>Keywords</th>
          <th>Price</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <%= render @images %>
      </tbody>
    </table>

  </div>
</section>

app/views/carts/_item.html.erb
<tr>
  <td>
    <%= image_tag image.image.tiny %>
  </td>
  <td>
    <h4><%= image.name %></h4>
    <br>
    <p><%= image.description %></p>
  </td>
  <td>$
    <%=  image.price_cents %>
  </td>
  <td>
    <%= button_to remove_item_cart_path(image_id: image.id), class: 'btn btn-xs btn-danger' do %> - <% end %>
    <%= quantity %>
    <%= button_to add_item_cart_path(image_id: image.id), class: 'btn btn-xs btn-success' do %> + <% end %>
  </td>
  <td>$
    <%= image.price_cents * quantity %>
  </td>
</tr>

app/views/carts/show.html.erb
<section class="cart-show">

  <header class="page-header">
    <h1>My Cart</h1>
  </header>

  <% if enhanced_cart.length == 0 %>
  <div class="alert alert-info" role="alert">
  Your cart is empty. Shop our images to add to your cart.
  </div>  

  <% else %>
  <div class="panel panel-default items">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Image</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Image Price</th>
        </tr>
      </thead>
      <tbody>
        <% enhanced_cart.each do |item| %>
          <%= render 'item', image: item[:image], quantity: item[:quantity].to_i %>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th colspan="4">
            TOTAL:
          </th>
          <th>$
            <%=  cart_subtotal_cents %>
          </th>
        </tr>
      </tfoot>
    </table>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <button class='btn btn-outline-primary btn-lg'>
        <%= link_to 'Checkout', '/orders' %>
      </button>
    </div>
  </div>

  <%end%>

</section>

app/views/images/_image.html.erb
<article class="image">
  <header>
    <h4 class="name">
      <%= image.name %>
    </h4>
  </header>

  <p class="description">
    <%= image.description %>
  </p>

  <p class="image">
    <%= image_tag image.image.thumb, alt: image.name %>
  </p>

  <aside class="price">$
    <%=  image.price_cents %>
  </aside>

  <footer class="actions">
    <%= button_to add_item_cart_path(image_id: image.id), class: 'btn btn-primary' , method: :post do %>
      <%= fa_icon "shopping-cart", text: 'Add' %>
    <% end %>
  </footer>

</article>

app/views/images/index.html.erb
<section class="images-index">

  <header class="page-header">
      <h1>Image Repository</h1>
  </header>

  <% if alert %>
  <div class="alert alert-warning" role="alert">
  <%= alert %>
  </div>
  <%end%>
  

  <div class="images">
    <%= render @images %>
  </div>

</section>

app/views/images/new.html.erb
<section class="images-new">

  <header class="page-header">
    <h1>New Image</h1>
  </header>

  <div class="well">
    <%= link_to 'All images', [:images], class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [@image] do |form| %>

        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :price %>
          <%= form.text_field :price_cents, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :keywords %>
          <p>Enter in a list of keywords to help users search for this item.</p>
          <%= form.text_area :keywords, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :image %>
          <%= form.file_field :image %>
        </div>

        <%= form.submit 'Create image', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
  

</section>

app/views/images/search.html.erb
<section class="images-index">

  <header class="page-header">
      <h1>Seach Results</h1>
  </header>

  <div class="well">
    <%= link_to 'All images', [:images], class: 'btn btn-info' %>
  </div>
  
  <div class="images">
    <%= render @results %>
    </div>




</section>

app/views/layouts/_top_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Image Browser</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Home', :root %>
        </li>
        <li>
          <%= link_to 'New Image', '/new' %>
        </li>
        <li>
          <%= link_to 'Admin', [:admin, :root] %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <li>
        <%= form_tag(search_page_path, :method => "get", class: 'navbar-form navbar-left') do %>  
          <div class="input-group">  
            <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
            <div class="input-group-btn">  
              <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
            </div>  
          </div>  
        <% end %>
      </li>
      <li>
        <%= link_to cart_path do %>
          <%= fa_icon "shopping-cart" %> My Cart (<%= cart.size %>)
        <% end %>
      </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageRepo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/top_nav' %>
<main class="container">

    <%= yield %>
 </main>

</body>
</html>

app/views/orders/index.html.erb
<section class="order-confirmation">

  <header class="page-header">
    <h1>Your order was placed successully.</h1>
  </header>

  <div class="order-summary jumbotron">
    <h2>Thank you for your order! We hope you enjoyed browsing our images. </h2>
    <br>
    <h4>Return to the home page to continue shopping: </h4>
    <%= link_to 'All images', [:images], class: 'btn btn-info' %>
  </div>  

  <div class="images">
  </div>


</section>